containers: Fix constructor of ContainerError
Commit b7fd693b didn't follow the rest of the modules in terms of how a
per-module exception's constructor should be defined, accidentally
creating an infinite recursion in the chain of exception inheritance:
    *** RecursionError: maximum recursion depth exceeded while getting
        the repr of an object

    [ERROR]: An unexpected error occurred
    Traceback (most recent call last):
      File "<path>/libvirt-ci.git/lcitool/application.py", line 426, in run
        args.func(self, args)
      File "<path>/libvirt-ci.git/lcitool/application.py", line 415, in _action_container_run
        return self._container_run(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<path>/libvirt-ci.git/lcitool/application.py", line 408, in _container_run
        return engine.run(**container_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<path>/libvirt-ci.git/lcitool/containers/podman.py", line 26, in run
        return super().run(image, container_cmd, user, tempdir, env, datadir,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<path>/libvirt-ci.git/lcitool/containers/containers.py", line 347, in run
      File "<path>/libvirt-ci.git/lcitool/containers/containers.py", line 289, in _run
        f"Image '{image}:{tag}' not found in local cache. "
    lcitool.containers.containers.ContainerError: <exception str() failed>

fixes: b7fd693b2700bc5136451ef88b190bb017658aee

Signed-off-by: Erik Skultety <eskultet@redhat.com>