facts: Bump freebsd-current to 14-0-snap
Now that freebsd-13 is pointing at 13.2, it makes no sense for
freebsd-current (which is supposed to be bleeding edge) to be stuck at
13-0-snap.  For example, pointing to the older base leads to failures
such as this on libnbd:

Error: Error on dynamically loaded library: ./../dllmlnbd.so: /usr/local/lib/libgnutls.so.30: Undefined symbol "strverscmp@FBSD_1.7"

Since Cirrus is now able to use the 14-0-snap, updating to that
snapshot will give us coverage to even more forward-looking FreeBSD
setups.

Signed-off-by: Eric Blake <eblake@redhat.com>