guests: fix error reporting when package is not in mappings
If a non-existant package 'fish' is added to a project it would raise
an exception:

  $ lcitool  variables fedora-34 osinfo-db
  [ERROR]: An unexpected error occurred
  Traceback (most recent call last):
    File "/home/berrange/src/virt/libvirt-ci/guests/lcitool/bin/lcitool", line 36, in <module>
      Application().run(args)
    File "/home/berrange/src/virt/libvirt-ci/guests/lcitool/lcitool/application.py", line 317, in run
      args.func(self, args)
    File "/home/berrange/src/virt/libvirt-ci/guests/lcitool/lcitool/application.py", line 282, in _action_variables
      variables = VariablesFormatter().format(args.target,
    File "/home/berrange/src/virt/libvirt-ci/guests/lcitool/lcitool/formatters.py", line 583, in format
      _, _, varmap = self._generator_prepare(target,
    File "/home/berrange/src/virt/libvirt-ci/guests/lcitool/lcitool/formatters.py", line 282, in _generator_prepare
      varmap = self._generator_build_varmap(facts,
    File "/home/berrange/src/virt/libvirt-ci/guests/lcitool/lcitool/formatters.py", line 118, in _generator_build_varmap
      raise Exception(f"No mapping defined for {package}")
  Exception: No mapping defined for fish

This was lost when refactoring package resolution in

  commit 258885bf7ee715bf54eed9585a341d0cf75ded68
  Author: Erik Skultety <eskultet@redhat.com>
  Date:   Fri Jun 4 15:09:47 2021 +0200

    formatters: Switch to the package generic-to-actual name resolving code

In restoring this error reporting, we squash the exception stack trace:

  $ lcitool  variables fedora-34 osinfo-db
  Package generic name resolution failed: Package fish not present in mappings

Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>