Do not install valgrind on macOS
It will fail with:

  valgrind: Linux is required for this software.
  Error: An unsatisfied requirement failed this build.

Signed-off-by: Martin Kletzander <mkletzan@redhat.com>