print descriptive messages when assertions fail
For the comparison with "golden" files it is quite complicated to
understand what is different between the actual output and the expected
one.

Instead of just "assert x == y", do the comparison recursively on
lists/dictionaries/strings so that it is possible to have output like
this:

AssertionError: comparing against /home/pbonzini/work/upstream/libvirt-ci/tests/data/formatters/out/opensuse-leap-153-all-projects.Dockerfile, at line 191: expected '           python3-Pillow \\', got '           python39-base \\'

AssertionError: comparing against /home/pbonzini/work/upstream/libvirt-ci/tests/data/packages/out/opensuse-leap-153.yml, at dictionary item pypi: expected 7 items, got 13, first extra element: 'numpy'

AssertionError: comparing against /home/pbonzini/work/upstream/libvirt-ci/tests/data/packages/out/opensuse-leap-153.yml, at dictionary item pypi, at item 5: expected 'meson==0.56.0', got 'lxml'

Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>