guests: inventory: Check if Ansible inventory exists
If the inventory doesn't exist we get a traceback ending with:

    FileNotFoundError: [Errno 2] No such file or directory:
        '/home/<user>/.config/lcitool/inventory'

We need to check that the inventory exists before letting Ansible try
working with it.

Signed-off-by: Erik Skultety <eskultet@redhat.com>