mappings: Fix python3-build mapping on Ubuntu-2204
The python3-build system package is broken on Ubuntu 22.04 longterm [1]
resulting in the following:

    * Creating venv isolated environment...
    Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/build/__main__.py", line 372,
        in main built = build_call(
    File "/usr/lib/python3/dist-packages/build/__main__.py", line 202,
        in build_package out = _build(isolation, builder, outdir,
                                      distribution, config_settings,
                                      skip_dependency_check)
    File "/usr/lib/python3/dist-packages/build/__main__.py", line 140,
        in _build return _build_in_isolated_env(builder, outdir,
                                                distribution,
                                                config_settings)
    File "/usr/lib/python3/dist-packages/build/__main__.py", line 104,
        in _build_in_isolated_env with _IsolatedEnvBuilder() as env:
    File "/usr/lib/python3/dist-packages/build/env.py", line 104, in
        __enter__ executable, scripts_dir =
        _create_isolated_env_venv(self._path)
    File "/usr/lib/python3/dist-packages/build/env.py", line 258, in
        create_isolated_env_venv executable, script_dir, purelib =
        _find_executable_and_scripts(path)
    File "/usr/lib/python3/dist-packages/build/env.py", line 303, in
        _find_executable_and_scripts
        raise RuntimeError(f'Virtual environment creation failed,
                           executable {executable} missing')
    RuntimeError: Virtual environment creation failed, executable
        /tmp/build-env-ybwlbk0z/local/bin/python missing
    ERROR Virtual environment creation failed, executable
        /tmp/build-env-ybwlbk0z/local/bin/python missing

What the above means is that we're not able to execute a PEP-517 build
using 'python3 -m build' which makes use of the native 'venv' module.
Fix this by falling back to a PyPI version of the 'build' module.

[1] https://bugs.launchpad.net/ubuntu/+source/python-build/+bug/1992108

Signed-off-by: Erik Skultety <eskultet@redhat.com>