containers: Assume 'latest' as the default tag
When commit 7fc18a6f moved the code in question from the application
module to the containers module, it missed an important bit - setting a
default value for the 'tag' variable which now causes:

    UnboundLocalError: cannot access local variable 'tag' where it is
    not associated with a value

fixes: 7fc18a6fb7f3d99de6d7907c5f06c5f7926787b0

Signed-off-by: Erik Skultety <eskultet@redhat.com>