guests: add openvz repository on CentOS 7
The OpenVZ site provides a yum repo built against RHEL-7 that includes
the prlsdk-devel RPM needed for the VZ driver. This repo has quite alot
of packages that replace stuff from standard RHEL repos, so the yum
config file is set to whitelist only the minimal RPMs we need to do
builds. Fortunately they have no deps which would cause replacement of
standard RHEL RPMs.

Note this does not use the latest OpenVZ repo link, since that currently
has broken dependencies present

Error: Package: libprlcommon-7.0.183-1.vz7.x86_64 (vz)
           Requires: libjson-c.so.2(libjson-c.so.2)(64bit)

The Requires line ought to be

   libjson-c.so.2()(64bit)

Once that's fixed we can switch to the latest repo link.

Reviewed-by: Andrea Bolognani <abologna@redhat.com>
Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>